parameters:
  dnd_manufacturer.array_converter.standard_to_flat.attribute.google.class: Dnd\Bundle\GoogleManufacturerBundle\ArrayConverter\StandardToFlat\Attribute\Google

services:
  dnd_manufacturer.array_converter.standard_to_flat.attribute.google:
    class: '%dnd_manufacturer.array_converter.standard_to_flat.attribute.google.class%'
    parent: pim_connector.array_converter.standard_to_flat.product_localized
