parameters:
  dnd_google_manufacturer.job.job_parameters.default_values_provider.product_xml_export.class: Dnd\Bundle\GoogleManufacturerBundle\Job\JobParameters\DefaultValuesProvider\ProductXmlExport

services:
  dnd_google_manufacturer.job.job_parameters.default_values_provider.product_xml_export:
    class: '%dnd_google_manufacturer.job.job_parameters.default_values_provider.product_xml_export.class%'
    arguments:
      - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_export'
      - '@pim_catalog.repository.channel'
      - '@pim_catalog.repository.locale'
      -
        - 'google_manufacturer_xml_product_export'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }