parameters:
  dnd_google_manufacturer.job.job_parameters.constraint_collection_provider.product_xml_export.class: Dnd\Bundle\GoogleManufacturerBundle\Job\JobParameters\ConstraintCollectionProvider\ProductXmlExport

services:
  dnd_google_manufacturer.job.job_parameters.constraint_collection_provider.product_xml_export:
    class: '%dnd_google_manufacturer.job.job_parameters.constraint_collection_provider.product_xml_export.class%'
    arguments:
      - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_export'
      -
        - 'google_manufacturer_xml_product_export'
      - '@translator'
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }