config:
  config:
    pim/fetcher-registry:
      fetchers:
        attributes-list:
          module: pim/base-fetcher
          options:
            urls:
              list: dnd_google_manufacturer_attribute_rest_list

  paths:
    # Modules extension
    dnd/common/add-select: dndgooglemanufacturer/js/product/edit/google/grouped/select

    dnd/job/export/product/edit/google:           dndgooglemanufacturer/js/product/edit/google
    dnd/job/export/product/edit/google/field:     dndgooglemanufacturer/js/product/edit/google/field
    dnd/job/export/product/edit/google/mandatory: dndgooglemanufacturer/js/product/edit/google/mandatory
    dnd/job/export/product/edit/google/optional:  dndgooglemanufacturer/js/product/edit/google/optional
    dnd/job/export/product/edit/google/grouped:   dndgooglemanufacturer/js/product/edit/google/grouped

    dnd/job/export/product/edit/google/grouped/feature-description: dndgooglemanufacturer/js/product/edit/google/grouped/feature-description
    dnd/job/export/product/edit/google/grouped/product-detail:      dndgooglemanufacturer/js/product/edit/google/grouped/product-detail

    # Templates
    dnd/template/export/common/edit/field/select:       dndgooglemanufacturer/templates/export/common/edit/field/select.html

    dnd/template/export/product/edit/google:            dndgooglemanufacturer/templates/export/product/edit/google.html
    dnd/template/export/product/edit/google/mandatory:  dndgooglemanufacturer/templates/export/product/edit/google/mandatory.html
    dnd/template/export/product/edit/google/optional:   dndgooglemanufacturer/templates/export/product/edit/google/optional.html
    dnd/template/export/product/edit/google/grouped:    dndgooglemanufacturer/templates/export/product/edit/google/grouped.html

    dnd/template/export/product/edit/google/grouped/feature-description:  dndgooglemanufacturer/templates/export/product/edit/google/grouped/feature-description.html
    dnd/template/export/product/edit/google/grouped/product-detail:       dndgooglemanufacturer/templates/export/product/edit/google/grouped/product-detail.html

