parameters:
  dnd_google_manufacturer.writer.file.xml_product.class: Dnd\Bundle\GoogleManufacturerBundle\Writer\File\Xml\Writer

services:
  dnd_google_manufacturer.writer.file.xml_product:
    class: '%dnd_google_manufacturer.writer.file.xml_product.class%'
    arguments:
      - '@dnd_manufacturer.array_converter.standard_to_flat.attribute.google'
      - '@pim_connector.factory.flat_item_buffer'
      - '@pim_connector.writer.file.flat_item_buffer_flusher'
      - '@pim_catalog.repository.channel'
      - '@pim_catalog.repository.attribute'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
