services:
  dnd_google_manufacturer.controller.rest.attribute:
    class: Dnd\Bundle\GoogleManufacturerBundle\Controller\Rest\AttributeController
    parent: pim_enrich.controller.rest.attribute

  dnd_google_manufacturer.controller.rest.google_grouped_attribute:
    class: Dnd\Bundle\GoogleManufacturerBundle\Controller\Rest\GoogleGroupedAttributeController

  dnd_google_manufacturer.controller.rest.google:
    class: Dnd\Bundle\GoogleManufacturerBundle\Controller\Rest\GoogleController
    arguments:
      - '@translator'
      - '@pim_user.context.user'
      - '%kernel.default_locale%'