services:
  dnd_google_manufacturer.job.job_parameters.constraint_collection_provider.product_xml_export:
    class: Dnd\GoogleManufacturerBundle\Connector\Job\JobParameters\ConstraintCollectionProvider\ProductXmlExport
    arguments:
      - '@akeneo_pim_enrichment.job.job_parameters.constraint_collection_provider.simple_csv_export'
      -
        - 'google_manufacturer_xml_product_export'
      - '@translator'
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }