services:
  dnd_google_manufacturer.job.job_parameters.default_values_provider.product_xml_export:
    class: Dnd\GoogleManufacturerBundle\Connector\Job\JobParameters\DefaultValuesProvider\ProductXmlExport
    arguments:
      - '@akeneo_pim_enrichment.job.job_parameters.default_values_provider.simple_csv_export'
      - '@pim_catalog.repository.channel'
      - '@pim_catalog.repository.locale'
      -
        - 'google_manufacturer_xml_product_export'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }